### ISSUE TITLE
java.awt.Scrollbar is invisible in Safari

### ISSUE THREAD

**Issue by oeway** [leaningtech/cheerpj-meta#99]
`java.awt.Scrollbar` is rendered as a scroll bar in the webpage, it becomes invisible for most of the browsers on MacOS (didn't test other OS).

For Chrome, I used the following CSS:
```css
::-webkit-scrollbar {
  -webkit-appearance: none;
  border-radius: 6px;
  background: rgba(0, 0, 0, 0.1);
}

::-webkit-scrollbar-thumb {
  border-radius: 6px;
  background-color: rgba(0, 0, 0, 0.25);
  -webkit-box-shadow: 0 0 1px rgba(255, 255, 255, 0.5);
}
```
so it works as expected:

<img width="164" alt="Screenshot 2020-09-05 at 03 00 49" src="https://user-images.githubusercontent.com/478667/92293464-0a5dc500-ef24-11ea-90cd-acb56181eec1.png">

However, it doesn't show in Firefox, nor in Safari:

<img width="156" alt="Screenshot 2020-09-05 at 03 02 13" src="https://user-images.githubusercontent.com/478667/92293480-3ed18100-ef24-11ea-9e45-072648e79222.png">

I did some research and it seems there is no way to force showing them, e.g. in Firefox. In that case, we may need a different implementation of the scroll bar to be consistent with the java implementation.

EDIT: for some reason, I can see the scrollbar in Firefox now, but still not in Safari.
